# Generated by Django 6.0.7 on 2026-10-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=150)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='print_settings/')),
                ('footer_text', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'print_settings',
            },
        ),
    ]
