# Generated by Django 6.0.7 on 2026-08-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('calculation_type', models.CharField(choices=[('percentage_of_value', 'Percentage of Total Value'), ('fixed_per_bale', 'Fixed Amount per Bale')], max_length=30)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Percentage value (e.g. 2.5 for 2.5%) or fixed USD amount, depending on calculation_type.', max_digits=8)),
                ('currency_treatment', models.CharField(choices=[('usd', 'USD'), ('zig', 'ZIG'), ('split', 'Split USD/ZIG')], default='usd', max_length=10)),
                ('is_permanent', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'deduction_rules',
                'ordering': ['order', 'name'],
            },
        ),
    ]
