# Generated by Django 6.0.7 on 2026-08-19 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('growers', '0001_initial'),
        ('saledates', '0001_initial'),
        ('transporters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('Harare', 'Harare'), ('Karoi', 'Karoi'), ('Rusape', 'Rusape'), ('Mvurwi', 'Mvurwi')], max_length=20, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'branch_dn_counters',
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('date_received', models.DateField()),
                ('branch', models.CharField(choices=[('Harare', 'Harare'), ('Karoi', 'Karoi'), ('Rusape', 'Rusape'), ('Mvurwi', 'Mvurwi')], max_length=20)),
                ('number_of_bales', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('weighed', 'Weighed'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes_created', to=settings.AUTH_USER_MODEL)),
                ('grower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='growers.grower')),
                ('sale_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='saledates.saledate')),
                ('transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='transporters.transporter')),
            ],
            options={
                'db_table': 'delivery_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
