# Generated by Django 6.0.7 on 2026-09-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverynotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='deductions_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
