# Generated by Django 6.0.7 on 2026-09-29 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weighing', '0003_bale_scanned_barcode_alter_bale_ticket_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('Harare', 'Harare'), ('Karoi', 'Karoi'), ('Rusape', 'Rusape'), ('Mvurwi', 'Mvurwi')], max_length=20)),
                ('truck_registration', models.CharField(max_length=30)),
                ('driver_name', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=150)),
                ('dispatch_date', models.DateField()),
                ('is_open', models.BooleanField(default=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dispatch_loads',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchLoadBale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('bale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_item', to='weighing.bale')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dispatch.dispatchload')),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dispatch_load_bales',
                'ordering': ['scanned_at'],
            },
        ),
    ]
