# Generated by Django 6.0.7 on 2026-08-06 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='grades',
        ),
        migrations.AddField(
            model_name='buyer',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Only one buyer can be the current active buyer system-wide.'),
        ),
        migrations.CreateModel(
            name='BuyerGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='buyers.buyer')),
            ],
            options={
                'db_table': 'buyer_grades',
                'ordering': ['code'],
                'unique_together': {('buyer', 'code')},
            },
        ),
    ]
