# Generated by Django 6.0.7 on 2026-08-19 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('Harare', 'Harare'), ('Karoi', 'Karoi'), ('Rusape', 'Rusape'), ('Mvurwi', 'Mvurwi')], max_length=20)),
                ('date', models.DateField()),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('is_open', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_dates_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_dates_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sale_dates',
                'ordering': ['-date'],
                'unique_together': {('branch', 'date')},
            },
        ),
    ]
