# Generated by Django 6.0.7 on 2026-08-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledate',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
