# Generated by Django 6.0.7 on 2026-10-01 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliverynotes', '0002_deliverynote_deductions_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedTicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('Harare', 'Harare'), ('Karoi', 'Karoi'), ('Rusape', 'Rusape'), ('Mvurwi', 'Mvurwi')], max_length=20)),
                ('ticket_number', models.CharField(max_length=20)),
                ('group_number', models.PositiveIntegerField()),
                ('lot_number', models.PositiveIntegerField()),
                ('hessian_code', models.CharField(max_length=5)),
                ('mass', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_ticket_logs', to='deliverynotes.deliverynote')),
            ],
            options={
                'db_table': 'deleted_ticket_logs',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
