# Generated by Django 6.0.7 on 2026-09-21 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weighing', '0003_bale_scanned_barcode_alter_bale_ticket_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaleProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_grade', models.CharField(max_length=20)),
                ('price_per_kg', models.DecimalField(decimal_places=4, max_digits=8)),
                ('grade_mismatch', models.BooleanField(default=False)),
                ('price_mismatch', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('bale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing', to='weighing.bale')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bale_processing',
            },
        ),
    ]
