# Generated by Django 6.0.7 on 2026-08-27 10:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliverynotes', '0001_initial'),
        ('saledates', '0002_alter_saledate_exchange_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HessianCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='Hessian code must be 2-5 letters.', regex='^[A-Za-z]{2,5}$')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hessian_codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TicketBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('Harare', 'Harare'), ('Karoi', 'Karoi'), ('Rusape', 'Rusape'), ('Mvurwi', 'Mvurwi')], max_length=20)),
                ('start_number', models.PositiveIntegerField()),
                ('end_number', models.PositiveIntegerField()),
                ('next_number', models.PositiveIntegerField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ticket_books',
                'ordering': ['branch', 'start_number'],
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(choices=[('Harare', 'Harare'), ('Karoi', 'Karoi'), ('Rusape', 'Rusape'), ('Mvurwi', 'Mvurwi')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'scales',
                'unique_together': {('name', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='Bale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('Harare', 'Harare'), ('Karoi', 'Karoi'), ('Rusape', 'Rusape'), ('Mvurwi', 'Mvurwi')], max_length=20)),
                ('group_number', models.PositiveIntegerField()),
                ('lot_number', models.PositiveIntegerField()),
                ('hessian_code', models.CharField(max_length=5)),
                ('mass', models.PositiveIntegerField(help_text='Whole kilograms')),
                ('ticket_number', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bales', to='deliverynotes.deliverynote')),
                ('sale_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bales', to='saledates.saledate')),
                ('scale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weighing.scale')),
            ],
            options={
                'db_table': 'bales',
                'ordering': ['created_at'],
                'unique_together': {('delivery_note', 'lot_number')},
            },
        ),
    ]
