# Generated by Django 6.0.7 on 2026-08-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bale',
            name='ticket_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketbook',
            name='end_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketbook',
            name='next_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketbook',
            name='start_number',
            field=models.CharField(max_length=20),
        ),
    ]
