# Generated by Django 6.0.7 on 2026-08-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighing', '0002_alter_bale_ticket_number_alter_ticketbook_end_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bale',
            name='scanned_barcode',
            field=models.CharField(blank=True, help_text='Raw scan, including the check character, kept for audit.', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='bale',
            name='ticket_number',
            field=models.CharField(help_text='Base ticket number, without the Code 39 check character.', max_length=20, unique=True),
        ),
    ]
