# Generated by Django 6.0.7 on 2026-09-24 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliverynotes', '0002_deliverynote_deductions_completed_at'),
        ('growers', '0001_initial'),
        ('saledates', '0002_alter_saledate_exchange_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesheetCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('Harare', 'Harare'), ('Karoi', 'Karoi'), ('Rusape', 'Rusape'), ('Mvurwi', 'Mvurwi')], max_length=20, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'salesheet_counters',
            },
        ),
        migrations.CreateModel(
            name='Salesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('branch', models.CharField(choices=[('Harare', 'Harare'), ('Karoi', 'Karoi'), ('Rusape', 'Rusape'), ('Mvurwi', 'Mvurwi')], max_length=20)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('usd_split_percent', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
                ('total_mass', models.PositiveIntegerField(default=0)),
                ('gross_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('statutory_deductions_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('farmer_deductions_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('usd_portion', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('zig_portion', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bales_incomplete', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('recalculated_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_note', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='salesheet', to='deliverynotes.deliverynote')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesheets_generated', to=settings.AUTH_USER_MODEL)),
                ('grower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salesheets', to='growers.grower')),
                ('sale_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salesheets', to='saledates.saledate')),
            ],
            options={
                'db_table': 'salesheets',
            },
        ),
        migrations.CreateModel(
            name='SalesheetDeductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('statutory', 'Statutory'), ('farmer', 'Farmer')], max_length=20)),
                ('salesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_lines', to='salesheets.salesheet')),
            ],
            options={
                'db_table': 'salesheet_deduction_lines',
            },
        ),
    ]
