# Generated by Django 6.0.7 on 2026-09-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesheetdeductionline',
            name='usd_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesheetdeductionline',
            name='zig_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
