# Generated by Django 6.0.7 on 2026-09-30 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesheets', '0002_salesheetdeductionline_usd_amount_and_more'),
        ('weighing', '0003_bale_scanned_barcode_alter_bale_ticket_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesheetBaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.PositiveIntegerField()),
                ('lot_number', models.PositiveIntegerField()),
                ('mass', models.PositiveIntegerField()),
                ('buyer_grade', models.CharField(max_length=20)),
                ('price_per_kg', models.DecimalField(decimal_places=4, max_digits=8)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejection_description', models.CharField(blank=True, max_length=255, null=True)),
                ('bale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='weighing.bale')),
                ('salesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bale_lines', to='salesheets.salesheet')),
            ],
            options={
                'db_table': 'salesheet_bale_lines',
                'ordering': ['group_number', 'lot_number'],
            },
        ),
    ]
