# Generated by Django 6.0.7 on 2026-09-18 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0002_remove_buyer_grades_buyer_is_current_buyergrade'),
        ('weighing', '0003_bale_scanned_barcode_alter_bale_ticket_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPreProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timb_grade', models.CharField(max_length=20)),
                ('buyer_grade', models.CharField(max_length=20)),
                ('price_per_kg', models.DecimalField(decimal_places=4, max_digits=8)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_processing', to='weighing.bale')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pre_processed_tickets', to='buyers.buyer')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket_pre_processing',
            },
        ),
    ]
