# Generated by Django 6.0.7 on 2026-09-30 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weighing', '0003_bale_scanned_barcode_alter_bale_ticket_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rejection_codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RejectedBale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('bale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rejection', to='weighing.bale')),
                ('rejected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rejection_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rejected_bales', to='rejectedbales.rejectioncode')),
            ],
            options={
                'db_table': 'rejected_bales',
                'ordering': ['-rejected_at'],
            },
        ),
    ]
