# Generated by Django 6.0.7 on 2026-07-22 06:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branches',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Harare', 'Harare'), ('Karoi', 'Karoi'), ('Rusape', 'Rusape'), ('Mvurwi', 'Mvurwi')], max_length=20), blank=True, default=list, help_text='Branches this user has access to.'),
        ),
    ]
